# List of location names with "Lahore, Punjab"
locations = [
    'DHA Defence, Lahore, Punjab' 'Bahria Orchard, Lahore, Punjab'
 'Paragon City, Lahore, Punjab' 'Askari, Lahore, Punjab'
 'Khayaban-e-Amin, Lahore, Punjab' 'Nishtar Colony, Lahore, Punjab'
 'Central Park Housing Scheme, Lahore, Punjab'
 'New Lahore City, Lahore, Punjab' 'Bahria Nasheman, Lahore, Punjab'
 'Bahria Town, Lahore, Punjab' 'Eden, Lahore, Punjab'
 'State Life Housing Society, Lahore, Punjab'
 'Bankers Avenue Cooperative Housing Society, Lahore, Punjab'
 'Raiwind Road, Lahore, Punjab' 'Johar Town, Lahore, Punjab'
 'Highcourt Society, Lahore, Punjab' 'Thokar Niaz Baig, Lahore, Punjab'
 'Military Accounts Housing Society, Lahore, Punjab'
 'Defence Road, Lahore, Punjab' 'Multan Road, Lahore, Punjab'
 'Jubilee Town, Lahore, Punjab'
 'Punjab University Employees Society, Lahore, Punjab'
 'Al Noor Park Housing Society, Lahore, Punjab'
 'Harbanspura, Lahore, Punjab' 'Park View City, Lahore, Punjab'
 'Mughalpura, Lahore, Punjab' 'GT Road, Lahore, Punjab'
 'Rail Town (Canal City), Lahore, Punjab' 'Green City, Lahore, Punjab'
 'Lahore Medical Housing Society, Lahore, Punjab'
 'College Road, Lahore, Punjab' 'Ferozepur Road, Lahore, Punjab'
 'Architects Engineers Housing Society, Lahore, Punjab'
 'Sunfort Gardens, Lahore, Punjab' 'Canal Garden, Lahore, Punjab'
 'Kahna, Lahore, Punjab' 'Sanda, Lahore, Punjab' 'Gulberg, Lahore, Punjab'
 'DHA 11 Rahbar, Lahore, Punjab' 'Izmir Town, Lahore, Punjab'
 'LDA Avenue, Lahore, Punjab' 'Gulshan-e-Ravi, Lahore, Punjab'
 'Punjab Coop Housing Society, Lahore, Punjab'
 'Valencia Housing Society, Lahore, Punjab' 'Wapda Town, Lahore, Punjab'
 'Sue-e-Asal, Lahore, Punjab' 'EME Society, Lahore, Punjab'
 'IEP Engineers Town, Lahore, Punjab' 'Sheraz Town, Lahore, Punjab'
 'PCSIR Housing Scheme, Lahore, Punjab'
 'Allama Iqbal Town, Lahore, Punjab' 'Al Rehman Garden, Lahore, Punjab'
 'Main Canal Bank Road, Lahore, Punjab'
 'OPF Housing Scheme, Lahore, Punjab' 'Nasheman-e-Iqbal, Lahore, Punjab'
 'Gulshan-e-Lahore, Lahore, Punjab' 'Revenue Society, Lahore, Punjab'
 'Peco Road, Lahore, Punjab' 'Pine Avenue, Lahore, Punjab'
 'Gosha-e-Ahbab, Lahore, Punjab' 'Garden Town, Lahore, Punjab'
 'Pak Arab Housing Society, Lahore, Punjab' 'Abid Road, Lahore, Punjab'
 'Vital Homes Housing Scheme, Lahore, Punjab'
 'Sabzazar Scheme, Lahore, Punjab' 'Tariq Gardens, Lahore, Punjab'
 'Shadab Garden, Lahore, Punjab' 'Venus Housing Scheme, Lahore, Punjab'
 'Bedian Road, Lahore, Punjab' 'Sui Gas Housing Society, Lahore, Punjab'
 'Ghous Garden, Lahore, Punjab' 'Canal Fort II, Lahore, Punjab'
 'Nawab Town, Lahore, Punjab' 'Tricon Village, Lahore, Punjab'
 'Icon Valley, Lahore, Punjab' 'Mozang, Lahore, Punjab'
 'Dream Avenue Lahore, Lahore, Punjab' 'Chaudhary Colony, Lahore, Punjab'
 'Formanites Housing Scheme, Lahore, Punjab'
 'Chungi Amar Sadhu, Lahore, Punjab' 'Faisal Town, Lahore, Punjab'
 'IBL Housing Scheme, Lahore, Punjab' 'NFC 1, Lahore, Punjab'
 'Model Town, Lahore, Punjab' 'Cantt, Lahore, Punjab'
 'Shoukat Town, Lahore, Punjab' 'Chinar Bagh, Lahore, Punjab'
 'Sukh Chayn Gardens, Lahore, Punjab' 'New Garden Town, Lahore, Punjab'
 'Rehmanpura (Ferozpur Road), Lahore, Punjab'
 'Shalimar Link Road, Lahore, Punjab' 'Al-Hamd Park, Lahore, Punjab'
 'HBFC Housing Society, Lahore, Punjab' 'Divine Gardens, Lahore, Punjab'
 'TIP Housing Society, Lahore, Punjab'
 'Park Avenue Housing Scheme, Lahore, Punjab'
 'Ashraf Garden, Lahore, Punjab'
 'Punjab Govt Employees Society, Lahore, Punjab' 'Ichhra, Lahore, Punjab'
 'Beacon House Society, Lahore, Punjab' 'Rehan Garden, Lahore, Punjab'
 'Audit & Accounts Housing Society, Lahore, Punjab'
 'Rizwan Garden Scheme, Lahore, Punjab' 'Wagha Town, Lahore, Punjab'
 'PIA Housing Scheme, Lahore, Punjab' 'Manawan, Lahore, Punjab'
 'Al-Hafiz Town, Lahore, Punjab' 'PCSIR Staff Colony, Lahore, Punjab'
 'Lahore Motorway City, Lahore, Punjab'
 'Fazaia Housing Scheme, Lahore, Punjab'
 'Cavalry Extension, Lahore, Punjab'
 'Punjab Small Industries Colony, Lahore, Punjab'
 'Iqbal Park, Lahore, Punjab' 'Rehman Villas, Lahore, Punjab'
 'Hamza Town, Lahore, Punjab' 'Bagarian, Lahore, Punjab'
 'Bankers Co-operative Housing Society, Lahore, Punjab'
 'Shalimar Housing Scheme, Lahore, Punjab' 'Kamahan Road, Lahore, Punjab'
 'Township, Lahore, Punjab' 'Sami Town, Lahore, Punjab'
 'Marghzar Officers Colony, Lahore, Punjab'
 'UET Housing Society, Lahore, Punjab'
 'Lahore - Kasur Road, Lahore, Punjab' 'City Life Homes, Lahore, Punjab'
 'Noor Jahan Road, Lahore, Punjab' 'Public Health Society, Lahore, Punjab'
 'Grand Avenues Housing Scheme, Lahore, Punjab'
 'Alpha Society, Lahore, Punjab' 'New Super Town, Lahore, Punjab'
 'Shanghai Road, Lahore, Punjab' 'Tajpura, Lahore, Punjab'
 'Walton Road, Lahore, Punjab' 'Bankers Town, Lahore, Punjab'
 'Shershah Colony - Raiwind Road, Lahore, Punjab'
 'New Muslim Town, Lahore, Punjab' 'Al-Hamad Colony (AIT), Lahore, Punjab'
 'Taj Bagh Scheme, Lahore, Punjab'
 'Canal Bank Housing Scheme, Lahore, Punjab' 'Shahdara, Lahore, Punjab'
 'Cantt View Society, Lahore, Punjab' 'Ahlu Road, Lahore, Punjab'
 'Cavalry Ground, Lahore, Punjab' 'Zaheer Villas, Lahore, Punjab'
 'Abdalians Cooperative Housing Society, Lahore, Punjab'
 'Habib Homes, Lahore, Punjab'
 'T & T Aabpara Housing Society, Lahore, Punjab'
 'Muslim Town, Lahore, Punjab' 'Baghbanpura, Lahore, Punjab'
 'Government Employees Cooperative Housing Society (GECHS), Lahore, Punjab'
 'Lalazaar Garden, Lahore, Punjab' 'Manhala Road, Lahore, Punjab'
 'Defence Fort, Lahore, Punjab' 'Rehman Housing Society, Lahore, Punjab'
 'Gulshan View Residence Society, Lahore, Punjab'
 'Atari Saroba, Lahore, Punjab' 'Jamal Homes, Lahore, Punjab'
 'Samanabad, Lahore, Punjab' 'Raj Garh, Lahore, Punjab'
 'Islampura, Lahore, Punjab' 'Super Town, Lahore, Punjab'
 'GOR, Lahore, Punjab' 'Sharaqpur Road, Lahore, Punjab'
 'Al-Qayyum Garden, Lahore, Punjab' 'Shah Jamal, Lahore, Punjab'
 'Chughtai Garden, Lahore, Punjab'
 'Airline Housing Society, Lahore, Punjab' 'Shadman, Lahore, Punjab'
 'Al Jalil Garden, Lahore, Punjab'
 'Punjab Government Servant Housing Foundation, Lahore, Punjab'
 'Davis Road, Lahore, Punjab' 'West Wood Housing Society, Lahore, Punjab'
 'Ashiana-e-Quaid Housing Scheme, Lahore, Punjab'
 'Ring Road, Lahore, Punjab' 'Alfalah Town, Lahore, Punjab'
 'Land Breeze Housing Society, Lahore, Punjab'
 'Awasia Housing Society, Lahore, Punjab'
 'Samanzar Colony, Lahore, Punjab' 'Toheed Park, Lahore, Punjab'
 'New Chauburji Park, Lahore, Punjab' 'Mohafiz Town, Lahore, Punjab'
 'Krishan Nagar, Lahore, Punjab' 'Jail Road, Lahore, Punjab'
 'Lawrence Road, Lahore, Punjab' 'Eden Avenue Extension, Lahore, Punjab'
 'Sheraz Villas, Lahore, Punjab' 'Islamabad Colony, Lahore, Punjab'
 'Heir, Lahore, Punjab' 'Manawala, Lahore, Punjab'
 'New Samanabad, Lahore, Punjab' 'UMT Society, Lahore, Punjab'
 'Waris Road, Lahore, Punjab' 'Shahtaj Colony, Lahore, Punjab'
 'Iqbal Avenue, Lahore, Punjab' 'Maryam Town, Lahore, Punjab'
 'Rewaz Garden, Lahore, Punjab' 'Mateen Avenue, Lahore, Punjab'
 'Royal Residencia, Lahore, Punjab' 'Jallo, Lahore, Punjab'
 'Lahore Canal Bank Cooperative Housing Society, Lahore, Punjab'
 'Garhi Shahu, Lahore, Punjab' 'Chaman Park, Lahore, Punjab'
 'Zohra Homes, Lahore, Punjab' 'Upper Mall, Lahore, Punjab'
 'Zaitoon City, Lahore, Punjab' 'Rifle Range Road, Lahore, Punjab'
 'Rehman Gardens, Lahore, Punjab' 'Al Hamra Town, Lahore, Punjab'
 'Sham Nagar, Lahore, Punjab' 'Ilyas Colony, Lahore, Punjab'
 'Azam Gardens, Lahore, Punjab' 'Awan Town, Lahore, Punjab'
 'Clifton Colony, Lahore, Punjab' 'Al Haram Garden, Lahore, Punjab'
 'Guldasht Town, Lahore, Punjab' 'Judicial Colony, Lahore, Punjab'
 'Gulbahar Colony, Lahore, Punjab'
 'Green Cap Housing Society, Lahore, Punjab' 'Elite Town, Lahore, Punjab'
 'Al Madina Avenue, Lahore, Punjab'
 'BOR - Board of Revenue Housing Society, Lahore, Punjab'
 'Omega Homes, Lahore, Punjab' 'Khayaban-e-Jinnah Road, Lahore, Punjab'
 'Mustafa Town, Lahore, Punjab' 'Singhpura, Lahore, Punjab'
 'Afzal Park, Lahore, Punjab' 'Shah Alam Market, Lahore, Punjab'
 'Walton Railway Officers Colony, Lahore, Punjab'
 'Wahdat Colony, Lahore, Punjab' 'Sahafi Colony, Lahore, Punjab'
 'Aitchison Society, Lahore, Punjab' 'Aashiana Road, Lahore, Punjab'
 'UBL Housing Society, Lahore, Punjab' 'Green Fort, Lahore, Punjab'
 'Sher Ali Road, Lahore, Punjab' 'PAF Colony, Lahore, Punjab'
 'Islamia Park, Lahore, Punjab' 'Rasool Park, Lahore, Punjab'
 'Canal Burg, Lahore, Punjab' 'Real Cottages, Lahore, Punjab'
 'Emerald City, Lahore, Punjab' 'Shadbagh, Lahore, Punjab'
 'Green Town Sector D2, Lahore, Punjab' 'Canal View, Lahore, Punjab'
 'Al Faisal Town, Lahore, Punjab' 'Bahar Shah Road, Lahore, Punjab'
 'Hanif Park Harbanspura, Lahore, Punjab' 'Sajid Garden, Lahore, Punjab'
 'Begampura, Lahore, Punjab' 'Lahore Villas, Lahore, Punjab'
 'Kacha Ferozepur Road, Lahore, Punjab' 'Civil Defence, Lahore, Punjab'
 'Garrison Homes, Lahore, Punjab' 'Bhatta Chowk, Lahore, Punjab'
 'Cricketer Villas, Lahore, Punjab' 'Shahzada New Abadi, Lahore, Punjab'
 'Hassan Town, Lahore, Punjab' 'Al-Hafeez Garden Road, Lahore, Punjab'
 'Rehmanpura (Harbanspura), Lahore, Punjab' 'Salamatpura, Lahore, Punjab'
 'Zaman Colony, Lahore, Punjab' 'National Town, Lahore, Punjab'
 'Batapur, Lahore, Punjab' 'Sultan Town, Lahore, Punjab'
 'Mehar Fayaz Colony, Lahore, Punjab' 'Fateh Garh, Lahore, Punjab'
 'Ittehad Park, Lahore, Punjab'
 'Excise & Taxation Housing Scheme, Lahore, Punjab'
 'Nishat Colony, Lahore, Punjab' 'Nazir Garden Society, Lahore, Punjab'
 'Saqib Town, Lahore, Punjab' 'Mughal Homes, Lahore, Punjab'
 'Mansoorah, Lahore, Punjab' 'Saidpur, Lahore, Punjab'
 'Dubban Pura, Lahore, Punjab' 'Karim Park, Lahore, Punjab'
 'P & D Housing Society, Lahore, Punjab'
 'Saroba Gardens Housing Society, Lahore, Punjab'
 'Gulgasht Colony Rustam Park, Lahore, Punjab'
 'Sant Nagar, Lahore, Punjab' 'Mustafabad Lalyani, Lahore, Punjab'
 'Atomic Energy Society - PAEC, Lahore, Punjab'
 'Circular Road, Lahore, Punjab' 'Qilla Gujjar Singh, Lahore, Punjab'
 'Lahore - Jaranwala Road, Lahore, Punjab'
 'Bahria Education & Medical City, Lahore, Punjab'
 'Education Town, Lahore, Punjab' 'Pakki Thatti, Lahore, Punjab'
 'Green Acres Housing Society, Lahore, Punjab'
 'Dubai Town, Lahore, Punjab' 'Khayaban-e-Quaid, Lahore, Punjab'
 'Sadhoke, Lahore, Punjab' 'Aman Town, Lahore, Punjab'
 'Ahmad Avenue, Lahore, Punjab' 'Malipura, Lahore, Punjab'
 'Mian Amiruddin Park, Lahore, Punjab' 'Khayaban-e-Zohra, Lahore, Punjab'
 'Ali Alam Garden, Lahore, Punjab' 'Sozo Town, Lahore, Punjab'
 'Hajvery Housing Scheme, Lahore, Punjab' 'Daroghewala, Lahore, Punjab'
 'Gul Kali, Lahore, Punjab' 'Al-Hamd Garden, Lahore, Punjab'
 'Islam Nagar, Lahore, Punjab' 'Wafaqi Colony, Lahore, Punjab'
 'Green Park, Lahore, Punjab' 'Gul-e-Damin, Lahore, Punjab'
 'Qartaba Chowk, Lahore, Punjab' 'Al Hamad Colony, Lahore, Punjab'
 'Rajgarh Road, Lahore, Punjab'
 'Sadat Cooperative Housing Society (College Town), Lahore, Punjab'
 'Naz Town, Lahore, Punjab' 'Sadaat Town, Lahore, Punjab'
 'Chauburji, Lahore, Punjab' 'PIA Main Boulevard, Lahore, Punjab'
 'Jamil Town, Lahore, Punjab' 'Sodiwal, Lahore, Punjab'
 'Gajju Matah, Lahore, Punjab' 'Khayaban-e-Zafar, Lahore, Punjab'
 'Abbot Road, Lahore, Punjab' 'Lytton Road, Lahore, Punjab'
 'Ali Town, Lahore, Punjab' 'Madina Colony, Lahore, Punjab'
 'Rehman Park, Lahore, Punjab'
]

# def clean_location(location):
#     return f"'{location.replace('Lahore, Punjab', '').strip()}'"

# # Iterate over each location and clean the name
# cleaned_locations = [clean_location(location) for location in locations]

# # Print the cleaned locations in single quotes
# for location in cleaned_locations:
#     print(location)

# def clean_location(location):
#     return f"'{location.replace('Lahore, Punjab', '').strip()}'"

# # Iterate over each location and clean the name
# cleaned_locations = [clean_location(location) for location in locations]

# # Join all cleaned locations in a single string
# output = " ".join(cleaned_locations)

# # Print the final result
# print(output.lower())

import pandas as pd

data = pd.read_csv(r'/home/muhammad-ahmad-nadeem/Projects/Lahore_house_price_predictor/resources/lahore_housing_prices.csv')


print(data['Area'].unique()) #170
print(data['Type'].unique()) #4
print(data['Bath(s)'].unique())
print(data['Bedroom(s)'].unique())